### ISSUE TITLE
slstr-lst strip (as opposed to "chips" or "frames") are not detected

### ISSUE THREAD

**Issue by pjhartzell** [stactools-packages/sentinel3#18]
**Describe the bug**

slstr-lst strip geometries are not corrected. In

```python
if item.properties["s3:product_name"] == "slstr-lst" and item.id.endswith("_____"):
```

`item.id.endswith("_____")` is never `True` because the trailing underscores are stripped from the Item ID. Strip data does not have a frame number, so those trailing underscores are inserted as fill values. Brute force is to check for item ID length, something like `len(item.id) == 57`, which indicates there is no frame number (and, hence, the data is a "strip").

https://github.com/stactools-packages/sentinel3/blob/604505a173d1e5ca731f8a439dcbc0dfca45980a/src/stactools/sentinel3/stac.py#L342

**To reproduce**

Run `create_item` on a `slstr-lst` strip archive, e.g., `S3A_SL_2_LST____20160518T063623_20160518T081722_20180929T115803_6059_004_177______LR1_R_NT_003.SEN3`

**Expected behavior**
Strips to be detected.

**Comment by ircwaves** [comment]
Makes sense.  Missed it because that combo isn't in the pile of examples.  Is there a doc on how to make those data-less netcdf files?  I could add the one you referenced.

To use the same logic as before, I pulled the `instance_id` out of the file name instead.  That seems to line up with [Sentinel-3 anming conventions](https://sentinel.esa.int/web/sentinel/user-guides/sentinel-3-olci/naming-convention)
